# Generated by Django 3.2.10 on 2023-05-11 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.search'),
        ),
    ]
