# Generated by Django 3.2.10 on 2023-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_image_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='format',
            field=models.CharField(default='jpeg', max_length=10),
        ),
    ]
