# Generated by Django 4.2.1 on 2023-05-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_image_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
