# Generated by Django 4.2.1 on 2023-05-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='filename',
            new_name='content_type',
        ),
    ]
