# Generated by Django 4.2.1 on 2023-05-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_filename_image_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='unique_search_image',
            field=models.CharField(default='Whatever', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='content_type',
            field=models.CharField(max_length=64),
        ),
    ]
